name: Security Audit

on:
  schedule:
    - cron: "0 0 * * 1" # Se ejecuta cada lunes a medianoche
  push:
    paths:
      - "caply/package-lock.json"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Run NPM Audit
        run: npm audit --audit-level=high
        working-directory: ./caply
